# Does AI Hype Drive NVIDIA Stock Performance?

Automated data pipeline combining financial market data (yfinance) and search interest data (Google Trends API) for 2019 - 2026 analysis of AI-related market sentiment.

In the analysis below, we will check if and how Nvidia's valuation is impacted by artificial intelligence, semiconductors and Nvidia Google searches. NVIDIA was named as a bet on how big the AI market will grow. Since its products are highly correlated with AI, there was a need to add a benchmark. We have chosen Microsoft stock since it's less volatile and more immune to AI hype.
Apart from Nvidia and artificial intelligence searches, we have also added semiconductors.

Variables used:
*  NVDA Stock Daily Close Price - converted to monthly percentage change
*  MSFT Stock Daily Close Price - converted to monthly percentage change
*  Nvidia Google Trends - converted to monthly percentage change
*  Artificial intelligence Google Trends - converted to monthly percentage change
* Semiconductors Google Trends - converted to monthly percentage change

In [131]:
pd.options.display.float_format = '{:,.1f}'.format

# **1. Import statements**

In [132]:
!pip install yfinance
!pip install pytrends

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.10.0)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.0.7)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2026.5.20)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (13.9.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->curl_cffi>=0.7->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.7->yfinance) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.7->yfinance) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.7->yfinance) (0.1.2)
Requirement already satisfied: pytrends in /usr/local/lib/python3.12/dist-packages (4.9.2)
Requirement already satisfied: requests>=2.0 in /usr/local/lib/python3.12/dist-packages (from pytrends) (2.32.4)
Requirement already satisfied: pandas>=0.25 in /usr/local/lib/python3.12/dist-packages (from pytrends) (2.2.2)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from pytrends) (6.1.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25->pytrends) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25->pytrends) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25->pytrends) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25->pytrends) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0->pytrends) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0->pytrends) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0->pytrends) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0->pytrends) (2026.5.20)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25->pytrends) (1.17.0)

In [133]:
import pandas as pd
import plotly.express as px
import yfinance as yf
import pytrends.request as tr
import numpy as np

# **2. Data collection**

## **2.1. Yahoo Finance via yfinance**

In [219]:
NVDA = yf.download('NVDA', start='2018-12-31', end='2026-06-26')
MSFT = yf.download('MSFT', start='2018-12-31', end='2026-06-26')

/tmp/ipykernel_890/426087084.py:1: FutureWarning:

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_890/426087084.py:2: FutureWarning:

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

## **2.2. Google Trends via pytrends:**

In [220]:
pytrends = tr.TrendReq(hl='en-US',tz=360)
keywords = ['NVIDIA', 'artificial intelligence', 'semiconductors']
pytrends.build_payload(keywords, timeframe='2018-12-01 2026-06-26', geo='')
trends = pytrends.interest_over_time()
trends.head()

/usr/local/lib/python3.12/dist-packages/pytrends/request.py:260: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

            NVIDIA  artificial intelligence  semiconductors  isPartial
date
2018-12-01      32                        3               0      False
2019-01-01      28                        3               0      False
2019-02-01      28                        3               0      False
2019-03-01      24                        3               0      False
2019-04-01      22                        3               0      False

# **3. Data quality check**

In [221]:
def data_quality_check(df):
  print('This is the shape of df:\n')
  print(df.shape)
  print('\nThis is head and tail of df:\n')
  print(df.head())
  print(df.tail())
  print('\nAre there any NA values in df?\n')
  print(df.isnull().sum())
  print('\nAre there any duplicated rows in df?\n')
  print(df.duplicated().sum())
  print('\nWhat is the index (date) difference in df?\n')
  print(df.index.diff())
  print('\nWhat are the data types in df?\n')
  print(df.dtypes)
  print('\nWhat are the statistics of df?\n')
  print(df.describe())

## **3.1. Nvidia's Stocks dataset**

In [222]:
data_quality_check(NVDA)

This is the shape of df:

(1881, 5)

This is head and tail of df:

Price      Close High  Low Open     Volume
Ticker      NVDA NVDA NVDA NVDA       NVDA
Date
2018-12-31   3.3  3.4  3.3  3.4  465140000
2019-01-02   3.4  3.4  3.2  3.2  508752000
2019-01-03   3.2  3.3  3.2  3.3  705552000
2019-01-04   3.4  3.4  3.2  3.2  585620000
2019-01-07   3.6  3.6  3.4  3.4  709160000
Price      Close  High   Low  Open     Volume
Ticker      NVDA  NVDA  NVDA  NVDA       NVDA
Date
2026-06-18 210.7 211.4 206.5 207.3  241272000
2026-06-22 208.6 214.0 207.7 211.4  122041400
2026-06-23 200.0 203.8 200.0 202.2  153496200
2026-06-24 199.0 201.7 196.6 200.1  151810700
2026-06-25 195.7 200.8 192.1 200.1  149550000

Are there any NA values in df?

Price   Ticker
Close   NVDA      0
High    NVDA      0
Low     NVDA      0
Open    NVDA      0
Volume  NVDA      0
dtype: int64

Are there any duplicated rows in df?

0

What is the index (date) difference in df?

TimedeltaIndex([     NaT, '2 days', '1 days', '1 days', '3 days', '1 days',
                '1 days', '1 days', '1 days', '3 days',
                ...
                '1 days', '1 days', '3 days', '1 days', '1 days', '1 days',
                '4 days', '1 days', '1 days', '1 days'],
               dtype='timedelta64[ns]', name='Date', length=1881, freq=None)

What are the data types in df?

Price   Ticker
Close   NVDA      float64
High    NVDA      float64
Low     NVDA      float64
Open    NVDA      float64
Volume  NVDA        int64
dtype: object

What are the statistics of df?

Price    Close    High     Low    Open          Volume
Ticker    NVDA    NVDA    NVDA    NVDA            NVDA
count  1,881.0 1,881.0 1,881.0 1,881.0         1,881.0
mean      59.1    60.1    58.0    59.1   400,401,215.7
std       64.5    65.5    63.5    64.5   204,495,043.4
min        3.2     3.3     3.2     3.2    65,528,500.0
25%       12.8    13.0    12.6    12.8   241,004,800.0
50%       22.9    23.3    22.4    22.9   372,388,000.0
75%      113.6   116.0   110.7   112.9   511,616,000.0
max      235.5   236.3   229.0   229.6 2,511,528,000.0

## **3.2. Microsoft's Stocks dataset**

In [223]:
data_quality_check(MSFT)

This is the shape of df:

(1881, 5)

This is head and tail of df:

Price      Close High  Low Open    Volume
Ticker      MSFT MSFT MSFT MSFT      MSFT
Date
2018-12-31  94.6 95.4 93.6 94.4  33173800
2019-01-02  94.2 94.8 92.2 92.7  35329300
2019-01-03  90.7 93.3 90.5 93.2  42579100
2019-01-04  94.9 95.5 92.2 92.9  44060600
2019-01-07  95.1 96.2 94.1 94.7  35656100
Price      Close  High   Low  Open    Volume
Ticker      MSFT  MSFT  MSFT  MSFT      MSFT
Date
2026-06-18 379.4 381.4 373.3 377.8  59714200
2026-06-22 367.3 381.6 367.1 375.7  45171100
2026-06-23 373.9 377.2 370.7 372.4  40647600
2026-06-24 365.5 378.9 364.8 371.6  44509900
2026-06-25 352.8 364.2 349.2 362.8  66179000

Are there any NA values in df?

Price   Ticker
Close   MSFT      0
High    MSFT      0
Low     MSFT      0
Open    MSFT      0
Volume  MSFT      0
dtype: int64

Are there any duplicated rows in df?

0

What is the index (date) difference in df?

TimedeltaIndex([     NaT, '2 days', '1 days', '1 days', '3 days', '1 days',
                '1 days', '1 days', '1 days', '3 days',
                ...
                '1 days', '1 days', '3 days', '1 days', '1 days', '1 days',
                '4 days', '1 days', '1 days', '1 days'],
               dtype='timedelta64[ns]', name='Date', length=1881, freq=None)

What are the data types in df?

Price   Ticker
Close   MSFT      float64
High    MSFT      float64
Low     MSFT      float64
Open    MSFT      float64
Volume  MSFT        int64
dtype: object

What are the statistics of df?

Price    Close    High     Low    Open        Volume
Ticker    MSFT    MSFT    MSFT    MSFT          MSFT
count  1,881.0 1,881.0 1,881.0 1,881.0       1,881.0
mean     295.0   297.8   292.0   295.0  27,742,037.9
std      115.8   116.7   115.0   115.9  12,214,604.2
min       90.7    93.3    90.5    92.7   5,855,900.0
25%      205.3   206.9   203.2   204.9  19,774,700.0
50%      282.5   284.4   278.5   281.6  24,847,300.0
75%      402.0   405.4   398.1   402.3  32,063,300.0
max      538.7   551.0   537.4   550.8 128,855,300.0

## **3.3. Trends dataset**

In [224]:
data_quality_check(trends)

This is the shape of df:

(91, 4)

This is head and tail of df:

            NVIDIA  artificial intelligence  semiconductors  isPartial
date
2018-12-01      32                        3               0      False
2019-01-01      28                        3               0      False
2019-02-01      28                        3               0      False
2019-03-01      24                        3               0      False
2019-04-01      22                        3               0      False
            NVIDIA  artificial intelligence  semiconductors  isPartial
date
2026-02-01      66                       21               2      False
2026-03-01      72                       19               2      False
2026-04-01      74                       24               3      False
2026-05-01      96                       27               4      False
2026-06-01      79                       20               3       True

Are there any NA values in df?

NVIDIA                     0
artificial intelligence    0
semiconductors             0
isPartial                  0
dtype: int64

Are there any duplicated rows in df?

30

What is the index (date) difference in df?

TimedeltaIndex([      NaT, '31 days', '31 days', '28 days', '31 days',
                '30 days', '31 days', '30 days', '31 days', '31 days',
                '30 days', '31 days', '30 days', '31 days', '31 days',
                '29 days', '31 days', '30 days', '31 days', '30 days',
                '31 days', '31 days', '30 days', '31 days', '30 days',
                '31 days', '31 days', '28 days', '31 days', '30 days',
                '31 days', '30 days', '31 days', '31 days', '30 days',
                '31 days', '30 days', '31 days', '31 days', '28 days',
                '31 days', '30 days', '31 days', '30 days', '31 days',
                '31 days', '30 days', '31 days', '30 days', '31 days',
                '31 days', '28 days', '31 days', '30 days', '31 days',
                '30 days', '31 days', '31 days', '30 days', '31 days',
                '30 days', '31 days', '31 days', '29 days', '31 days',
                '30 days', '31 days', '30 days', '31 days', '31 days',
                '30 days', '31 days', '30 days', '31 days', '31 days',
                '28 days', '31 days', '30 days', '31 days', '30 days',
                '31 days', '31 days', '30 days', '31 days', '30 days',
                '31 days', '31 days', '28 days', '31 days', '30 days',
                '31 days'],
               dtype='timedelta64[ns]', name='date', freq=None)

What are the data types in df?

NVIDIA                     int64
artificial intelligence    int64
semiconductors             int64
isPartial                   bool
dtype: object

What are the statistics of df?

       NVIDIA  artificial intelligence  semiconductors
count    91.0                     91.0            91.0
mean     36.9                      6.0             0.5
std      20.0                      4.9             0.8
min      19.0                      3.0             0.0
25%      24.0                      3.0             0.0
50%      27.0                      4.0             0.0
75%      46.5                      6.0             1.0
max     100.0                     27.0             4.0

In [225]:
trends.index.duplicated().sum()

np.int64(0)

## **3.4. Findings and comments**

* The latest month (June 2026) contains incomplete data in all three datasets (25 days instead of a full month).
* Stock data is recorded every trading day, while trends are recorded monthly.
* First, looking at the trends dataset tells us that there are duplicates; however, since no duplicates were found in the index, it means that the trends were flat in certain periods, not that there are actually duplicated entries.

# **4. Data preparation**

## **4.1. Stocks data resampling**

For further analysis, NVDA and MSFT data need to be converted from daily to monthly. Month-end market valuation will be represented by the close price recorded on the last trading day of each month. For the purpose of clarity and in alignment with trends, the dataset month start date will be used as an index.

In [226]:
NVDA_monthly = NVDA.resample('MS').last()
MSFT_monthly = MSFT.resample('MS').last()

In [227]:
NVDA_monthly.shape

(91, 5)

In [228]:
MSFT_monthly.shape

(91, 5)

## **4.2. Monthly change calculation**

In [229]:
def pct_change_calculation(df, columnname, new_columnname):
  df[new_columnname] = df[columnname].pct_change()
  print(df.head())

In [230]:
pct_change_list = [
    [NVDA_monthly, 'Close', 'NVDA_change'],
    [MSFT_monthly, 'Close', 'MSFT_change'],
    [trends, 'NVIDIA', 't_NVIDIA'],
    [trends, 'artificial intelligence', 't_artificial intelligence'],
    [trends, 'semiconductors', 't_semiconductors']
]

In [231]:
for n in pct_change_list:
  pct_change_calculation(n[0], n[1], n[2])

Price      Close High  Low Open     Volume NVDA_change
Ticker      NVDA NVDA NVDA NVDA       NVDA
Date
2018-12-01   3.3  3.4  3.3  3.4  465140000         NaN
2019-01-01   3.6  3.6  3.4  3.4  842852000         0.1
2019-02-01   3.8  3.9  3.8  3.8  324944000         0.1
2019-03-01   4.5  4.5  4.4  4.5  456896000         0.2
2019-04-01   4.5  4.5  4.4  4.4  362920000         0.0
Price      Close  High   Low  Open    Volume MSFT_change
Ticker      MSFT  MSFT  MSFT  MSFT      MSFT
Date
2018-12-01  94.6  95.4  93.6  94.4  33173800         NaN
2019-01-01  97.3  98.0  96.1  96.7  55636400         0.0
2019-02-01 104.8 105.6 104.5 104.8  29083900         0.1
2019-03-01 110.3 110.7 109.4 110.5  25399800         0.1
2019-04-01 122.2 122.3 121.0 121.4  24166500         0.1
            NVIDIA  artificial intelligence  semiconductors  isPartial  \
date
2018-12-01      32                        3               0      False
2019-01-01      28                        3               0      False
2019-02-01      28                        3               0      False
2019-03-01      24                        3               0      False
2019-04-01      22                        3               0      False

            t_NVIDIA
date
2018-12-01       NaN
2019-01-01      -0.1
2019-02-01       0.0
2019-03-01      -0.1
2019-04-01      -0.1
            NVIDIA  artificial intelligence  semiconductors  isPartial  \
date
2018-12-01      32                        3               0      False
2019-01-01      28                        3               0      False
2019-02-01      28                        3               0      False
2019-03-01      24                        3               0      False
2019-04-01      22                        3               0      False

            t_NVIDIA  t_artificial intelligence
date
2018-12-01       NaN                        NaN
2019-01-01      -0.1                        0.0
2019-02-01       0.0                        0.0
2019-03-01      -0.1                        0.0
2019-04-01      -0.1                        0.0
            NVIDIA  artificial intelligence  semiconductors  isPartial  \
date
2018-12-01      32                        3               0      False
2019-01-01      28                        3               0      False
2019-02-01      28                        3               0      False
2019-03-01      24                        3               0      False
2019-04-01      22                        3               0      False

            t_NVIDIA  t_artificial intelligence  t_semiconductors
date
2018-12-01       NaN                        NaN               NaN
2019-01-01      -0.1                        0.0               NaN
2019-02-01       0.0                        0.0               NaN
2019-03-01      -0.1                        0.0               NaN
2019-04-01      -0.1                        0.0               NaN

For both of the price stock datasets, we have calculated the percentage change based on the close price.

For the **trends** dataset, we needed to calculate the percentage change for all three columns. This calculation for the first row will return NaN, so it was dropped from the dataset. Due to very little interest in semiconductors at the beginning of the dataset, the percentage change was changed from NaN (result from dividing 0 by 0) to 0.

## **4.4. Combining datasets**

In [232]:
trends_col = ['t_NVIDIA', 't_artificial intelligence', 't_semiconductors']

In [233]:
df = pd.concat(
    [NVDA_monthly['NVDA_change'],
     MSFT_monthly['MSFT_change'],
     trends[trends_col]],
    axis=1
    )

In [234]:
df_final = df.mul(100)

After successfully combining NVDA and MSFT stock price change with trends, the numbers were multiplied by 100 for a clearer view of the data.

In [235]:
df_final

,NVDA_change,MSFT_change,t_NVIDIA,t_artificial intelligence,t_semiconductors
2018-12-01,NaN,NaN,NaN,NaN,NaN
2019-01-01,7.7,2.8,-12.5,0.0,NaN
2019-02-01,7.4,7.7,0.0,0.0,NaN
2019-03-01,16.4,5.3,-14.3,0.0,NaN
2019-04-01,0.8,10.7,-8.3,0.0,NaN
...,...,...,...,...,...
2026-02-01,-7.3,-8.5,3.1,50.0,0.0
2026-03-01,-1.6,-5.7,9.1,-9.5,0.0
2026-04-01,14.4,10.2,2.8,26.3,50.0
2026-05-01,5.8,10.7,29.7,12.5,33.3
2026-06-01,-7.2,-21.6,-17.7,-25.9,-25.0

As expected, percentage change calculation for the first row returned NaN. It will be dropped from the dataset. Due to very little interest in semiconductors at the beginning of the chosen period, the percentage change will also be changed from NaN (result from dividing 0 by 0) to 0.

In [236]:
df_final = df_final.iloc[1:]
df_final.fillna(0, inplace=True)
df_final.head()

/tmp/ipykernel_890/3355284589.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,NVDA_change,MSFT_change,t_NVIDIA,t_artificial intelligence,t_semiconductors
2019-01-01,7.7,2.8,-12.5,0.0,0.0
2019-02-01,7.4,7.7,0.0,0.0,0.0
2019-03-01,16.4,5.3,-14.3,0.0,0.0
2019-04-01,0.8,10.7,-8.3,0.0,0.0
2019-05-01,-25.1,-4.9,-13.6,0.0,0.0

# **5. Final dataset analysis**

## **5.1. Final sense check**

In [237]:
data_quality_check(df_final)

This is the shape of df:

(90, 5)

This is head and tail of df:

            NVDA_change  MSFT_change  t_NVIDIA  t_artificial intelligence  \
2019-01-01          7.7          2.8     -12.5                        0.0
2019-02-01          7.4          7.7       0.0                        0.0
2019-03-01         16.4          5.3     -14.3                        0.0
2019-04-01          0.8         10.7      -8.3                        0.0
2019-05-01        -25.1         -4.9     -13.6                        0.0

            t_semiconductors
2019-01-01               0.0
2019-02-01               0.0
2019-03-01               0.0
2019-04-01               0.0
2019-05-01               0.0
            NVDA_change  MSFT_change  t_NVIDIA  t_artificial intelligence  \
2026-02-01         -7.3         -8.5       3.1                       50.0
2026-03-01         -1.6         -5.7       9.1                       -9.5
2026-04-01         14.4         10.2       2.8                       26.3
2026-05-01          5.8         10.7      29.7                       12.5
2026-06-01         -7.2        -21.6     -17.7                      -25.9

            t_semiconductors
2026-02-01               0.0
2026-03-01               0.0
2026-04-01              50.0
2026-05-01              33.3
2026-06-01             -25.0

Are there any NA values in df?

NVDA_change                  0
MSFT_change                  0
t_NVIDIA                     0
t_artificial intelligence    0
t_semiconductors             0
dtype: int64

Are there any duplicated rows in df?

0

What is the index (date) difference in df?

TimedeltaIndex([      NaT, '31 days', '28 days', '31 days', '30 days',
                '31 days', '30 days', '31 days', '31 days', '30 days',
                '31 days', '30 days', '31 days', '31 days', '29 days',
                '31 days', '30 days', '31 days', '30 days', '31 days',
                '31 days', '30 days', '31 days', '30 days', '31 days',
                '31 days', '28 days', '31 days', '30 days', '31 days',
                '30 days', '31 days', '31 days', '30 days', '31 days',
                '30 days', '31 days', '31 days', '28 days', '31 days',
                '30 days', '31 days', '30 days', '31 days', '31 days',
                '30 days', '31 days', '30 days', '31 days', '31 days',
                '28 days', '31 days', '30 days', '31 days', '30 days',
                '31 days', '31 days', '30 days', '31 days', '30 days',
                '31 days', '31 days', '29 days', '31 days', '30 days',
                '31 days', '30 days', '31 days', '31 days', '30 days',
                '31 days', '30 days', '31 days', '31 days', '28 days',
                '31 days', '30 days', '31 days', '30 days', '31 days',
                '31 days', '30 days', '31 days', '30 days', '31 days',
                '31 days', '28 days', '31 days', '30 days', '31 days'],
               dtype='timedelta64[ns]', freq=None)

What are the data types in df?

NVDA_change                  float64
MSFT_change                  float64
t_NVIDIA                     float64
t_artificial intelligence    float64
t_semiconductors             float64
dtype: object

What are the statistics of df?

       NVDA_change  MSFT_change  t_NVIDIA  t_artificial intelligence  \
count         90.0         90.0      90.0                       90.0
mean           5.5          1.7       2.7                        2.9
std           13.3          6.9      19.7                       13.1
min          -32.0        -21.6     -30.8                      -25.9
25%           -2.5         -3.7      -7.9                        0.0
50%            5.7          1.7       0.0                        0.0
75%           14.3          6.8       9.4                        0.0
max           36.3         17.6      74.5                       62.5

       t_semiconductors
count              90.0
mean                inf
std                 NaN
min              -100.0
25%                 0.0
50%                 0.0
75%                 0.0
max                 inf

While we don't have any NA values, it seems we have inf values in t_semiconductor, probably because we have divided by 0.

In [238]:
np.isinf(df_final).sum()

NVDA_change                  0
MSFT_change                  0
t_NVIDIA                     0
t_artificial intelligence    0
t_semiconductors             6
dtype: int64

In [239]:
df_final.replace([np.inf, -np.inf], np.nan, inplace=True)
df_final.fillna(0, inplace=True)

/tmp/ipykernel_890/1827835224.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_890/1827835224.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [240]:
df_final.describe()

,NVDA_change,MSFT_change,t_NVIDIA,t_artificial intelligence,t_semiconductors
count,90.0,90.0,90.0,90.0,90.0
mean,5.5,1.7,2.7,2.9,-3.8
std,13.3,6.9,19.7,13.1,26.6
min,-32.0,-21.6,-30.8,-25.9,-100.0
25%,-2.5,-3.7,-7.9,0.0,0.0
50%,5.7,1.7,0.0,0.0,0.0
75%,14.3,6.8,9.4,0.0,0.0
max,36.3,17.6,74.5,62.5,100.0

## 5.2. Stock price volatility

In [241]:
line_fig = px.line(df_final,
                   x=df_final.index,
                   y=['NVDA_change', 'MSFT_change'])

line_fig.update_layout(title='<b>NVDA vs. MSFT - stock price volatility 2019-2026</b>',
                       title_x=0.5,
                       xaxis_title='<b>Period</b>',
                       yaxis_title='<b>Monthly Stock Price % Change</b>',
                       legend_title_text='<b>Variables</b>',
                       legend=dict(font=dict(size=10)))

line_fig.add_vline(x='2022-11-01',
                   line_width=2,
                   line_dash='dash',
                   line_color='black')

line_fig.add_annotation(
    x='2022-11-01',
    y=0.85,
    xref='x',
    yref='paper',
    text='<b>CHATGPT LAUNCH</b><br>Key AI catalyst <br>(Q4 2022)',
    showarrow=True,
    arrowhead=2,
    arrowcolor='black',
    ax=-80,
    ay=-40,
    bgcolor='white',
    font=dict(size=10, color='black')
)

line_fig.add_vline(
    x='2024-05-01',
    line_width=2,
    line_dash='dash',
    line_color='black'
)

line_fig.add_annotation(
    x='2024-05-01',
    y=0.85,
    xref='x',
    yref='paper',
    text='<b>THE BLACKWELL SUPERCHIP</b><br>Key NVDA Catalyst <br>(Q1 2024)',
    showarrow=True,
    arrowhead=2,
    arrowcolor='black',
    ax=-80,
    ay=-40,
    bgcolor='white',
    font=dict(size=10, color='black'))

line_fig.add_vline(
    x='2025-08-01',
    line_width=2,
    line_dash='dash',
    line_color='black'
)

line_fig.add_annotation(
    x='2025-08-01',
    y=0.85,
    xref='x',
    yref='paper',
    text='<b>PEAK OF PUBLIC AWARNESS</b><br>Key Semicondutors Catalyst <br>(Q3 2025)',
    showarrow=True,
    arrowhead=2,
    arrowcolor='black',
    ax=-40,
    ay=-40,
    bgcolor='white',
    font=dict(size=10, color='black'))

line_fig.show()

Nvidia's stock price is consistently more volatile than Microsoft's stock price. It is also visible in basic dataset statistics, as NVDA change mean is 5.5% while MSFT mean is only 1.7%.

## 5.3. Trends
* When did the AI trend start?
* Does Nvidia's and semiconductors search reflect an AI search pattern?

In [242]:
line_fig_2 = px.line(df_final,
                     x=df_final.index,
                     y=['t_artificial intelligence','t_NVIDIA', 't_semiconductors'])

line_fig_2.update_layout(title='<b>Google Search Trends - AI, Nvidia and semiconductors</b>',
                         title_x=0.5,
                         xaxis_title='<b>Period</b>',
                         yaxis_title='<b>Monthly Search Index % Change</b>',
                         legend_title_text='<b>Variables</b>',
                         legend=dict(font=dict(size=10)))

line_fig_2.add_vline(x='2022-11-01',
                   line_width=2,
                   line_dash='dash',
                   line_color='black')

line_fig_2.add_annotation(
    x='2022-11-01',
    y=0.8,
    xref='x',
    yref='paper',
    text='<b>CHATGPT LAUNCH</b><br>Key AI catalyst <br>(Q4 2022)',
    showarrow=True,
    arrowhead=2,
    arrowcolor='black',
    ax=-80,
    ay=-40,
    bgcolor='white',
    font=dict(size=10, color='black')
)

line_fig_2.add_vline(
    x='2024-05-01',
    line_width=2,
    line_dash='dash',
    line_color='black'
)

line_fig_2.add_annotation(
    x='2024-05-01',
    y=0.8,
    xref='x',
    yref='paper',
    text='<b>THE BLACKWELL SUPERCHIP</b><br>Key NVDA Catalyst <br>(Q1 2024)',
    showarrow=True,
    arrowhead=2,
    arrowcolor='black',
    ax=-80,
    ay=-40,
    bgcolor='white',
    font=dict(size=10, color='black'))

line_fig_2.add_vline(
    x='2025-08-01',
    line_width=2,
    line_dash='dash',
    line_color='black'
)

line_fig_2.add_annotation(
    x='2025-08-01',
    y=0.8,
    xref='x',
    yref='paper',
    text='<b>PEAK OF PUBLIC AWARNESS</b><br>Key Semicondutors Catalyst <br>(Q3 2025)',
    showarrow=True,
    arrowhead=2,
    arrowcolor='black',
    ax=-40,
    ay=-40,
    bgcolor='white',
    font=dict(size=10, color='black'))


line_fig_2.show()

When talking about the AI era, the launch of ChatGPT (November 2022) is usually named as the starting point. While the artificial intelligence trend has grown since that point, the most rapid growth is visible in the second half of 2025 (August).

Based on the line chart, we see that around the same time, there is similar movement for the other two searches, most notably in semiconductors. Up to that point, it seems that it was a niche topic, but in August 2025, both Nvidia searches and semiconductor searches followed the rapid growth pattern of the AI trend.

If we search the news for August 2025, we will learn that the "public awareness" was triggered by the debut of Blackwell Chip, a new Nvidia product advertised as AI dedicated hardware accounting for high computation demands, which resulted in record-shattering Nvidia valuation.

## 5.4. Correlation

One thing consistently visible in both stock and trend charts is how volatile percentage change numbers can be month over month. For correlation analysis, it would be advised to instead use a 3-month rolling average to smooth out the data.

In [243]:
df_final = df_final.rolling(window=3).mean().dropna()

In [244]:
df_final

,NVDA_change,MSFT_change,t_NVIDIA,t_artificial intelligence,t_semiconductors
2019-03-01,10.5,5.3,-8.9,0.0,0.0
2019-04-01,8.2,7.9,-7.5,0.0,0.0
2019-05-01,-2.6,3.7,-12.1,0.0,0.0
2019-06-01,-1.0,4.7,-3.8,0.0,0.0
2019-07-01,-0.4,1.7,-1.0,0.0,0.0
...,...,...,...,...,...
2026-02-01,0.2,-7.1,-12.1,14.4,0.0
2026-03-01,-2.1,-8.4,-0.4,11.3,0.0
2026-04-01,1.9,-1.4,5.0,22.3,16.7
2026-05-01,6.2,5.0,13.9,9.8,27.8
2026-06-01,4.3,-0.3,4.9,4.3,19.4

In [245]:
corr = df_final.corr()
corr

,NVDA_change,MSFT_change,t_NVIDIA,t_artificial intelligence,t_semiconductors
NVDA_change,1.0,0.7,0.2,0.1,-0.0
MSFT_change,0.7,1.0,-0.0,-0.1,-0.1
t_NVIDIA,0.2,-0.0,1.0,0.3,0.2
t_artificial intelligence,0.1,-0.1,0.3,1.0,0.3
t_semiconductors,-0.0,-0.1,0.2,0.3,1.0

Most notable results are:
*  0.7 correlation between NVDA and MSFT stocks,
*  0.3 correlation between Nvidia and artificial intelligence searches,
*  0.3 correlation between Nvidia and semiconductor searches,
*  0.3 correlation between artificial intelligence and semiconductor searches.

In [246]:
heatmap = px.imshow(corr,
                    text_auto=".2f",
                    title='<b>Correlation Heatmap</b>',
                    color_continuous_scale='Rainbow',
                    zmin=-1,
                    zmax=1)
heatmap.update_layout(title_x=0.5)

heatmap.show()

What if we checked the correlation for a shorter period of time? Especially choosing Chat GPT launch as a starting point.

In [247]:
df_final_ai = df_final.loc['2022-11-01':]

In [248]:
df_final_ai.shape

(44, 5)

In [249]:
corr_ai = df_final_ai.corr()
corr_ai

,NVDA_change,MSFT_change,t_NVIDIA,t_artificial intelligence,t_semiconductors
NVDA_change,1.0,0.7,0.2,0.2,-0.2
MSFT_change,0.7,1.0,0.1,0.0,-0.3
t_NVIDIA,0.2,0.1,1.0,0.3,0.2
t_artificial intelligence,0.2,0.0,0.3,1.0,0.4
t_semiconductors,-0.2,-0.3,0.2,0.4,1.0

In [250]:
corr_diff = corr_ai - corr
corr_diff

,NVDA_change,MSFT_change,t_NVIDIA,t_artificial intelligence,t_semiconductors
NVDA_change,0.0,-0.0,-0.1,0.1,-0.2
MSFT_change,-0.0,0.0,0.1,0.1,-0.2
t_NVIDIA,-0.1,0.1,0.0,-0.0,0.1
t_artificial intelligence,0.1,0.1,-0.0,0.0,0.1
t_semiconductors,-0.2,-0.2,0.1,0.1,0.0

In [251]:
heatmap_ai = px.imshow(corr_ai,
                    text_auto=".2f",
                    title='<b>Correlation Heatmap</b><br>since ChatGPT launch',
                    color_continuous_scale='Rainbow',
                    zmin=-1,
                    zmax=1)
heatmap_ai.update_layout(title_x=0.5)

heatmap_ai.show()

After shortening the period of our analysis, we can see that there is a higher correlation between trends. Interestingly, it seems that semiconductor searches have a reverse correlation to both NVDA and MSFT stock prices.

## 5.5. Stocks Lag Analysis

In the prior part, we were analysing whether the change in trends has a direct response in the stock market. However, often there is a time lag between a rise in interest and actual movement from investors. Let's see if AI hype drives the stock price.

Since we will proceed with at least three similar operations let's define a few functions:

In [252]:
def lag_calculation(df, columnname, lag):
  df[columnname] = df[columnname].shift(lag)

We are also checking trends vs. stock price, so there is no need for a whole correlation matrix.

In [253]:
trends_list = ['t_NVIDIA', 't_artificial intelligence', 't_semiconductors']

In [254]:
stocks_list = ['NVDA_change', 'MSFT_change']

For each correalation matrix we will also need a heatmap.

In [255]:
def lag_corr_calculation(df, corr_df, heatmap_name):
  df.dropna(inplace=True)
  corr_df = df.corr()
  corr_df = corr_df.loc[trends_list, stocks_list]
  print(corr_df)
  heatmap_name = px.imshow(corr_df,
                      text_auto=".2f",
                      title='<b>Correlation Heatmap</b>',
                      color_continuous_scale='Rainbow',
                      zmin=-1,
                      zmax=1)
  heatmap_name.update_layout(title_x=0.5)

  heatmap_name.show()

### 5.5.1. One-Month Lag

Let's create necessary dataframes.

In [256]:
df_final_1M = df_final.copy()

In [257]:
corr_1M = pd.DataFrame()
heatmap_1M = px.imshow

In [217]:
for stock in stocks_list:
  lag_calculation(df_final_1M, stock, -1)

In [218]:
df_final_1M

,NVDA_change,MSFT_change,t_NVIDIA,t_artificial intelligence,t_semiconductors
2019-03-01,8.2,7.9,-8.9,0.0,0.0
2019-04-01,-2.6,3.7,-7.5,0.0,0.0
2019-05-01,-1.0,4.7,-12.1,0.0,0.0
2019-06-01,-0.4,1.7,-3.8,0.0,0.0
2019-07-01,7.8,3.8,-1.0,0.0,0.0
...,...,...,...,...,...
2026-02-01,-2.1,-8.4,-12.1,14.4,0.0
2026-03-01,1.9,-1.4,-0.4,11.3,0.0
2026-04-01,6.2,5.0,5.0,22.3,16.7
2026-05-01,4.3,-0.3,13.9,9.8,27.8
2026-06-01,NaN,NaN,4.9,4.3,19.4

In [258]:
lag_corr_calculation(df_final_1M, corr_1M, heatmap_1M)

                           NVDA_change  MSFT_change
t_NVIDIA                           0.2         -0.0
t_artificial intelligence          0.1         -0.1
t_semiconductors                  -0.0         -0.1

One-month lag analysis shows slight changes, but nothing notable.

### 5.5.2. Two-Month Lag

In [259]:
df_final_2M = df_final.copy()
corr_2M = pd.DataFrame()
heatmap_2M = px.imshow

In [260]:
for stock in stocks_list:
  lag_calculation(df_final_2M, stock, -2)

In [261]:
df_final_2M

,NVDA_change,MSFT_change,t_NVIDIA,t_artificial intelligence,t_semiconductors
2019-03-01,-2.6,3.7,-8.9,0.0,0.0
2019-04-01,-1.0,4.7,-7.5,0.0,0.0
2019-05-01,-0.4,1.7,-12.1,0.0,0.0
2019-06-01,7.8,3.8,-3.8,0.0,0.0
2019-07-01,2.0,1.4,-1.0,0.0,0.0
...,...,...,...,...,...
2026-02-01,1.9,-1.4,-12.1,14.4,0.0
2026-03-01,6.2,5.0,-0.4,11.3,0.0
2026-04-01,4.3,-0.3,5.0,22.3,16.7
2026-05-01,NaN,NaN,13.9,9.8,27.8
2026-06-01,NaN,NaN,4.9,4.3,19.4

In [262]:
lag_corr_calculation(df_final_2M, corr_2M, heatmap_2M)

                           NVDA_change  MSFT_change
t_NVIDIA                          -0.1         -0.3
t_artificial intelligence         -0.0         -0.1
t_semiconductors                   0.0          0.0

Two-month lag analysis also shows slight changes signalling reverse correlation, most notably -0.3 correlation between NVIDIA searches and MSFT stock price.

### 5.5.3. Three-Month Lag

In [263]:
df_final_3M = df_final.copy()
corr_3M = pd.DataFrame()
heatmap_3M = px.imshow

In [264]:
for stock in stocks_list:
  lag_calculation(df_final_3M, stock, -3)

In [265]:
df_final_3M

,NVDA_change,MSFT_change,t_NVIDIA,t_artificial intelligence,t_semiconductors
2019-03-01,-1.0,4.7,-8.9,0.0,0.0
2019-04-01,-0.4,1.7,-7.5,0.0,0.0
2019-05-01,7.8,3.8,-12.1,0.0,0.0
2019-06-01,2.0,1.4,-3.8,0.0,0.0
2019-07-01,6.3,1.8,-1.0,0.0,0.0
...,...,...,...,...,...
2026-02-01,6.2,5.0,-12.1,14.4,0.0
2026-03-01,4.3,-0.3,-0.4,11.3,0.0
2026-04-01,NaN,NaN,5.0,22.3,16.7
2026-05-01,NaN,NaN,13.9,9.8,27.8
2026-06-01,NaN,NaN,4.9,4.3,19.4

In [266]:
lag_corr_calculation(df_final_3M, corr_3M, heatmap_3M)

                           NVDA_change  MSFT_change
t_NVIDIA                          -0.2         -0.3
t_artificial intelligence         -0.1         -0.2
t_semiconductors                   0.1          0.1

For the three-month lag analysis, we are back to nothing notable.

## 5.6. Trends Lag Analysis

What if the reverse happens, and it's actually stock market news that is influencing the general public to google articles' keywords?

### 5.6.1. One-Month Lag

In [267]:
df_final_1M_t = df_final.copy()
corr_1M_t = pd.DataFrame()
heatmap_1M_t = px.imshow

In [268]:
for stock in stocks_list:
  lag_calculation(df_final_1M_t, stock, 1)

In [269]:
df_final_1M_t

,NVDA_change,MSFT_change,t_NVIDIA,t_artificial intelligence,t_semiconductors
2019-03-01,NaN,NaN,-8.9,0.0,0.0
2019-04-01,10.5,5.3,-7.5,0.0,0.0
2019-05-01,8.2,7.9,-12.1,0.0,0.0
2019-06-01,-2.6,3.7,-3.8,0.0,0.0
2019-07-01,-1.0,4.7,-1.0,0.0,0.0
...,...,...,...,...,...
2026-02-01,-1.6,-5.8,-12.1,14.4,0.0
2026-03-01,0.2,-7.1,-0.4,11.3,0.0
2026-04-01,-2.1,-8.4,5.0,22.3,16.7
2026-05-01,1.9,-1.4,13.9,9.8,27.8
2026-06-01,6.2,5.0,4.9,4.3,19.4

In [270]:
lag_corr_calculation(df_final_1M_t, corr_1M_t, heatmap_1M_t)

                           NVDA_change  MSFT_change
t_NVIDIA                           0.3          0.2
t_artificial intelligence          0.1         -0.1
t_semiconductors                   0.0         -0.0

One-month lag for trends shows that there is higher correlation between NVDA stock price and NVIDIA searches.

### 5.6.2. Two-Month Lag

In [271]:
df_final_2M_t = df_final.copy()
corr_2M_t = pd.DataFrame()
heatmap_2M_t = px.imshow

In [272]:
for stock in stocks_list:
  lag_calculation(df_final_2M_t, stock, 2)

In [273]:
df_final_2M_t

,NVDA_change,MSFT_change,t_NVIDIA,t_artificial intelligence,t_semiconductors
2019-03-01,NaN,NaN,-8.9,0.0,0.0
2019-04-01,NaN,NaN,-7.5,0.0,0.0
2019-05-01,10.5,5.3,-12.1,0.0,0.0
2019-06-01,8.2,7.9,-3.8,0.0,0.0
2019-07-01,-2.6,3.7,-1.0,0.0,0.0
...,...,...,...,...,...
2026-02-01,0.4,-2.2,-12.1,14.4,0.0
2026-03-01,-1.6,-5.8,-0.4,11.3,0.0
2026-04-01,0.2,-7.1,5.0,22.3,16.7
2026-05-01,-2.1,-8.4,13.9,9.8,27.8
2026-06-01,1.9,-1.4,4.9,4.3,19.4

In [274]:
lag_corr_calculation(df_final_2M_t, corr_2M_t, heatmap_2M_t)

                           NVDA_change  MSFT_change
t_NVIDIA                           0.3          0.3
t_artificial intelligence          0.1          0.1
t_semiconductors                   0.1          0.2

For Two-Month Trends Lag, we see the highest correlation in our analysis with NVIDIA searches vs NVDA and MSFT stock prices.

### 5.6.3. Three-Month Lag

In [275]:
df_final_3M_t = df_final.copy()
corr_3M_t = pd.DataFrame()
heatmap_3M_t = px.imshow

In [276]:
for stock in stocks_list:
  lag_calculation(df_final_3M_t, stock, 3)

In [277]:
df_final_3M_t

,NVDA_change,MSFT_change,t_NVIDIA,t_artificial intelligence,t_semiconductors
2019-03-01,NaN,NaN,-8.9,0.0,0.0
2019-04-01,NaN,NaN,-7.5,0.0,0.0
2019-05-01,NaN,NaN,-12.1,0.0,0.0
2019-06-01,10.5,5.3,-3.8,0.0,0.0
2019-07-01,8.2,7.9,-1.0,0.0,0.0
...,...,...,...,...,...
2026-02-01,1.0,-0.9,-12.1,14.4,0.0
2026-03-01,0.4,-2.2,-0.4,11.3,0.0
2026-04-01,-1.6,-5.8,5.0,22.3,16.7
2026-05-01,0.2,-7.1,13.9,9.8,27.8
2026-06-01,-2.1,-8.4,4.9,4.3,19.4

In [278]:
lag_corr_calculation(df_final_3M_t, corr_3M_t, heatmap_3M_t)

                           NVDA_change  MSFT_change
t_NVIDIA                           0.3          0.3
t_artificial intelligence          0.1          0.0
t_semiconductors                   0.0          0.2

In the Three-Month Trend Lag analysis we see similar result to Two-Month Trend lag analysis.

# **6. Final conclusions**

1. Stock prices' volatility has confirmed our initial hypothesis that Microsoft stocks serve their purpose. MSFT price shows an association with AI hype; however, it is far less volatile.

2. The biggest boom in semiconductor trends happened after NVIDIA reached a record valuation in 2025; prior to that, based on Google Trends searches, it was a niche topic.

3. Stock prices for both NVIDIA and Microsoft are not directly impacted by trends in chosen Google searches, regardless of whether we check the same-month correlation or analyse one, two or three-month lag.

4. On the other hand, it seems that the stock market news is actually driving the hype, which is visible in the Two-Month and Three-Month Trend Lag. As no surprise, the general public hearing about NVIDIA's record-breaking valuation prompts people to find out what this is about. That would make NVIDIA searches a lagging indicator.

5. NVIDIA Google searches seem to be correlated with both artificial intelligence popularity and semiconductors.